/* AUTOGENERATED FILE - DO NOT EDIT CONTENTS */

export const projectId = "otspuziezueuoccmtjkd"
export const publicAnonKey = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im90c3B1emllenVldW9jY210amtkIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzIyMzUzMTUsImV4cCI6MjA4NzgxMTMxNX0.qFD_vX6ijE73anYinsBGiCyAOhlSwoOv4628R-WspAk"
